[package]
name = "SageMode"
version = "0.1.0"
description = "SageMode is a beautifully minimal macOS app that helps you visualize your daily app usage and focus patterns with precision. Track where your time goes, see which apps demand your attention, and uncover insights to boost productivity—all in a clean, dark-themed interface inspired by tools like Rize. Whether you're coding, exploring, or attending meetings, SageMode brings mindful awareness to your digital habits."
authors = ["Abhigyan Mohanta"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "sagemode_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sysinfo = { version = "0.30" }
core-graphics = "0.22.3"
objc = "0.2.7"
block = "0.1.6"

